/* Additive exploration and inference layer for Health Atlas.
 * Original v2/v3 applications, observations, comments and mathematical engine remain intact.
 * All new analytics use exact-year aggregate joins; no user health records are collected.
 */
(function(root){
  'use strict';
  const D=root.GLOBAL_HEALTH,M=root.AtlasMath,E=root.HealthEngine,Q=root.ATLAS_LAB.quadrature;
  const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const countries=new Map(D.countries.map(c=>[c.id,c])),regions=['EAS','ECS','LCN','MEA','NAC','SAS','SSF','OTH'];
  const palettes=['#2c8c75','#ad824e','#6b81bc','#b66068','#8b73b3','#638e9c','#849649','#758980'];
  let globe=null,globeEl=null,globeTicket=0,enhanceTimer=0,epoch=0,charts=new Map(),resizeObservers=new Map(),lastAnalysis=null,overlapFraction=.5;
  const loaders=new Map();
  function bridge(){return root.AtlasBridge;}
  function state(){return bridge().state();}
  function t(k){return bridge().t(k);}
  function name(id){return bridge().name(id);}
  function format(v,unit){return bridge().fmt(v,unit);}
  function metricName(id){return bridge().label(D.metrics[id]);}
  function pct(v){return format(v*100,'percent');}
  function decimal(v){return v==null?'—':format(v,'decimal');}
  function text(key){return esc(t(key));}
  function download(value,filename,mime='application/json'){const content=typeof value==='string'?value:JSON.stringify(value,null,2);const u=URL.createObjectURL(new Blob([content],{type:mime})),a=document.createElement('a');a.href=u;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
  function load(kind){const ready=kind==='three'?root.AtlasThree:root.AtlasECharts;if(ready)return Promise.resolve(ready);if(loaders.has(kind))return loaders.get(kind);const p=new Promise((resolve,reject)=>{
    const script=document.createElement('script');script.src=new URL(`./v4/vendor/${kind}.bundle.js`,document.baseURI).href;script.onload=()=>resolve(kind==='three'?root.AtlasThree:root.AtlasECharts);script.onerror=()=>{loaders.delete(kind);script.remove();reject(new Error('Visualization bundle failed'));};document.head.appendChild(script);
  });loaders.set(kind,p);return p;}
  function disposeCharts(){charts.forEach(c=>c.dispose());charts.clear();resizeObservers.forEach(r=>r.disconnect());resizeObservers.clear();}
  function cleanup(){epoch++;clearTimeout(enhanceTimer);disposeCharts();if(globe){globe.dispose?.();globe=null;}globeEl=null;globeTicket++;}
  function prune(){for(const [id,c]of charts){if(!c.getDom().isConnected){c.dispose();charts.delete(id);resizeObservers.get(id)?.disconnect();resizeObservers.delete(id);}}if(globeEl&&!globeEl.isConnected){globe?.dispose?.();globe=null;globeEl=null;globeTicket++;}}
  function chart(id,option,click){const el=$('#'+id);if(!el)return;el.setAttribute('aria-busy','true');
    load('echarts').then(({echarts})=>{if(!el.isConnected)return;let c=charts.get(id);if(c&&c.getDom()!==el){c.dispose();resizeObservers.get(id)?.disconnect();c=null;}
      if(!c){c=echarts.init(el,null,{renderer:'canvas',devicePixelRatio:Math.min(devicePixelRatio||1,1.5)});charts.set(id,c);const ro=new ResizeObserver(()=>{if(!c.isDisposed())c.resize();});ro.observe(el);resizeObservers.set(id,ro);}
      c.setOption({...option,animation:!matchMedia('(prefers-reduced-motion: reduce)').matches,animationDuration:220,aria:{enabled:true,label:{enabled:true}}},true);c.off('click');if(click)c.on('click',click);el.setAttribute('aria-busy','false');el.dataset.chartReady='true';
    }).catch(()=>{if(el.isConnected){el.innerHTML=`<p class="notice warning">${text('graphFallback')}</p>`;el.setAttribute('aria-busy','false');}});
  }
  function theme(){const s=getComputedStyle(document.documentElement);return {ink:s.getPropertyValue('--ink').trim(),muted:s.getPropertyValue('--muted').trim(),line:s.getPropertyValue('--line').trim(),accent:s.getPropertyValue('--accent').trim(),paper:s.getPropertyValue('--paper').trim(),orange:s.getPropertyValue('--orange').trim()};}
  function baseChart(){const c=theme();return {textStyle:{color:c.ink,fontFamily:'Arial, sans-serif'},grid:{left:65,right:28,top:35,bottom:75},tooltip:{trigger:'item',confine:true,backgroundColor:c.paper,borderColor:c.line,textStyle:{color:c.ink}},xAxis:{type:'value',min:0,axisLabel:{color:c.muted},splitLine:{lineStyle:{color:c.line}},axisLine:{show:true,lineStyle:{color:c.line}}},yAxis:{type:'value',min:0,axisLabel:{color:c.muted},splitLine:{lineStyle:{color:c.line}}}};}
  function readParams(s,p){
    s.x=D.metrics[p.get('x')]?p.get('x'):s.x||'obesity';s.yMetric=D.metrics[p.get('z')]?p.get('z'):s.yMetric||'diabetes_who';
    const years=D.metrics[s.x].years.filter(y=>D.metrics[s.yMetric].years.includes(y));const candidate=Number(p.get('ay')||s.analysisYear||2022);
    s.analysisYear=years.includes(candidate)?candidate:years.at(-1)||2022;
    s.analysisRegion=regions.includes(p.get('region'))?p.get('region'):'';
    const sy=Number(p.get('from')||s.changeStart||2010),ey=Number(p.get('to')||s.changeEnd||s.analysisYear),my=D.metrics[s.yMetric].years;
    s.changeEnd=my.includes(ey)?ey:my.at(-1);s.changeStart=my.includes(sy)&&sy<s.changeEnd?sy:my.find(y=>y<s.changeEnd)||s.changeEnd;
  }
  function writeParams(s,p){if(s.page!=='insights')return;for(const [key,value]of Object.entries({x:s.x,z:s.yMetric,ay:s.analysisYear,region:s.analysisRegion,from:s.changeStart,to:s.changeEnd}))if(value!==undefined&&value!=='')p.set(key,String(value));}
  function globeOptions(options){return {...options,onFailure:()=>fallback(options)};}
  function fallback(options){if(!globeEl||!globeEl.isConnected)return;const el=globeEl,zoom=el.querySelector('.map-zoom');zoom?.remove();globe?.dispose?.();globe=null;el.classList.remove('pro-globe');el.dataset.renderer='fallback';const c=root.AtlasCharts.createMap(el,options),msg=document.createElement('p');msg.className='pro-fallback';msg.textContent=t('globeFallback');el.appendChild(msg);if(zoom)el.appendChild(zoom);root.ATLAS_GLOBE_STATE={mode:'fallback'};globe=c;}
  function createGlobe(el,options){
    const maxValue=Math.max(1,...Object.values(options.metric.series).flatMap(s=>s.map(p=>p[1]))),max=options.metric.unit==='percent'?Math.min(100,Math.ceil(maxValue/10)*10):Math.ceil(maxValue/10)*10;
    const wrapper={max,symbols:options.metric.unit==='people',zoomIn:()=>globe?.zoomIn(),zoomOut:()=>globe?.zoomOut(),reset:()=>globe?.reset()};
    if(globeEl===el&&globe?.update){globe.update(globeOptions(options));root.ATLAS_GLOBE_STATE={mode:'three',country:options.country,year:options.year};return wrapper;}
    globe?.dispose?.();globe=null;globeEl=el;const ticket=++globeTicket;
    el.innerHTML=`<div class="pro-viz-loading" role="status">${text('loadingViz')}</div>`;
    if(root.ATLAS_DISABLE_WEBGL){fallback(options);return wrapper;}
    load('three').then(lib=>{if(ticket!==globeTicket||!el.isConnected)return;try{const words=Object.fromEntries(['globeHint','rotate','stopRotate','focus','downloadPNG'].map(k=>[k,t(k)]));const zoom=el.querySelector('.map-zoom');globe=root.AtlasGlobe.mount(el,globeOptions(options),lib,words);if(zoom)el.appendChild(zoom);root.ATLAS_GLOBE_STATE={mode:'three',country:options.country,year:options.year};}catch(error){root.ATLAS_GLOBE_ERROR=String(error);fallback(options);}}).catch(()=>{if(ticket===globeTicket)fallback(options);});return wrapper;
  }
  function options(selected){return D.order.map(id=>`<option value="${id}"${id===selected?' selected':''}>${esc(metricName(id))}</option>`).join('');}
  function notice(k){return `<p class="notice pro-notice">${text(k)}</p>`;}
  function stat(label,value,note=''){return `<div class="pro-stat"><span>${esc(label)}</span><strong>${esc(value)}</strong>${note?`<small>${esc(note)}</small>`:''}</div>`;}
  function selectedRecord(rows){const row=rows.find(r=>r.id===state().country);return row||null;}
  function recordView(rows){const s=state(),r=selectedRecord(rows);return `<div class="pro-selected"><span class="pro-small">${text('selected')} · ${s.country}</span><h2>${esc(name(s.country))}</h2>${[s.x,s.yMetric].map((m,i)=>`<div class="pro-side-metric"><span>${esc(metricName(m))}</span><strong>${r?format(i?r.y:r.x,D.metrics[m]):'—'}</strong><small>${text(D.metrics[m].age)} · ${text(D.metrics[m].measure)}</small><button class="source-link" data-source="${m}">${text('source')} ↗</button></div>`).join('')}<p class="pro-small">${s.analysisYear} · ${r?text('matched'):text('missingNote')}</p></div>`;}
  function renderInsights(){cleanup();const s=state();readParams(s,new URLSearchParams(location.hash.split('?')[1]||''));bridge().set(s,false);const years=D.metrics[s.x].years.filter(y=>D.metrics[s.yMetric].years.includes(y)),j=M.join(D,s.x,s.yMetric,s.analysisYear,s.analysisRegion),warn=M.metadataWarnings(D.metrics[s.x],D.metrics[s.yMetric]);
    lastAnalysis=M.exportRecord(D,{x:s.x,y:s.yMetric,year:s.analysisYear,region:s.analysisRegion},j);root.ATLAS_ANALYSIS_RESULT=j;
    $('#content').innerHTML=`<section class="hero pro-hero"><div><h1>${text('insightTitle')}</h1><p class="intro">${text('insightIntro')}</p></div><button class="btn" data-pro="export-analysis">${text('exportAnalysis')}</button></section>
      <div class="pro-presets" role="group" aria-label="${text('preset')}">${[['obesity','diabetes_who'],['life','diabetes'],['diabetes_who','diabetes_who_c']].map(([x,y])=>`<button class="btn${s.x===x&&s.yMetric===y?' btn-primary':''}" data-pro-preset="${x}|${y}">${esc(metricName(x))} × ${esc(metricName(y))}</button>`).join('')}</div>
      <section class="atlas-panel pro-workbench"><div class="atlas-toolbar pro-insight-toolbar"><div class="field"><label for="pro-x">${text('xAxis')}</label><select id="pro-x">${options(s.x)}</select></div><div class="field"><label for="pro-y">${text('yAxis')}</label><select id="pro-y">${options(s.yMetric)}</select></div><div class="field"><label for="pro-year">${text('year')}</label><select id="pro-year">${years.slice().reverse().map(y=>`<option${y===s.analysisYear?' selected':''}>${y}</option>`).join('')}</select></div><div class="field"><label for="pro-region">${text('region')}</label><select id="pro-region"><option value="">${text('allRegions')}</option>${regions.map(r=>`<option value="${r}"${r===s.analysisRegion?' selected':''}>${text(r)}</option>`).join('')}</select></div></div>
      <div class="pro-analysis-layout"><div class="pro-analysis-left"><div class="pro-stat-row">${stat(t('matched'),String(j.n))}${stat('Spearman ρ',decimal(j.spearman))}${stat('Pearson r',decimal(j.pearson))}</div><div class="pro-scatter-title">${esc(metricName(s.yMetric))} × ${esc(metricName(s.x))} · ${s.analysisYear}<button class="source-link" data-pro="export-scatter">${text('downloadPNG')} ↓</button></div><div id="pro-scatter" class="pro-chart" role="img" aria-label="${text('insightIntro')}"></div><div class="pro-region-key">${regions.filter(r=>j.rows.some(row=>row.region===r)).map(r=>`<span><i style="background:${palettes[regions.indexOf(r)]}"></i>${text(r)}</span>`).join('')}</div><p class="pro-chart-note">${text('equalDots')}<br>${text('chartHint')}</p></div><aside id="pro-selected">${recordView(j.rows)}</aside></div></section>
      <div class="pro-reading-notes">${notice('ecological')}${warn.differentAge||warn.differentMeasure?notice('unitMismatch'):''}<p class="small muted">${text('excluded')}：${j.missing} / ${j.eligible} · ${text('retrieved')} ${D.meta.retrieved}</p></div>
      <details class="pro-table-details"><summary>${text('showRows')} · ${j.n}</summary><div class="table-scroll"><table class="data-table"><thead><tr><th>${text('country')}</th><th>${esc(metricName(s.x))}</th><th>${esc(metricName(s.yMetric))}</th><th>${text('year')}</th></tr></thead><tbody>${j.rows.map(r=>`<tr><td><button class="country-link" data-pro-country="${r.id}">${esc(name(r.id))}</button></td><td>${format(r.x,D.metrics[s.x])}</td><td>${format(r.y,D.metrics[s.yMetric])}</td><td>${r.year}</td></tr>`).join('')}</tbody></table></div></details><section class="pro-changes" id="pro-changes"></section>`;
    const c=theme(),base=baseChart();
    chart('pro-scatter',{...base,xAxis:{...base.xAxis,name:metricName(s.x)+' · '+bridge().unit(D.metrics[s.x]),nameLocation:'middle',nameGap:42,nameTextStyle:{fontSize:11}},yAxis:{...base.yAxis,name:bridge().unit(D.metrics[s.yMetric]),nameTextStyle:{fontSize:11}},dataZoom:[{type:'slider',height:16,bottom:5,showDetail:false,filterMode:'none',borderColor:c.line,handleSize:'120%',brushSelect:false}],tooltip:{...base.tooltip,formatter:p=>`${esc(name(p.data.id))}<br>${esc(metricName(s.x))}: ${format(p.data.value[0],D.metrics[s.x])}<br>${esc(metricName(s.yMetric))}: ${format(p.data.value[1],D.metrics[s.yMetric])}<br>${s.analysisYear}`},series:regions.map((r,i)=>({name:t(r),type:'scatter',symbolSize:10,itemStyle:{color:palettes[i],opacity:.8,borderColor:c.paper,borderWidth:.8},emphasis:{scale:1.8,focus:'self'},data:j.rows.filter(row=>row.region===r).map(row=>({value:[row.x,row.y],id:row.id}))})).concat([{type:'scatter',name:t('selected'),symbolSize:20,itemStyle:{color:'transparent',borderColor:c.orange,borderWidth:2},label:{show:true,position:'top',color:c.ink,formatter:()=>name(s.country)},data:selectedRecord(j.rows)?[{value:[selectedRecord(j.rows).x,selectedRecord(j.rows).y],id:s.country}]:[]}])},e=>{if(e.data?.id)selectAnalysis(e.data.id);});
    renderChanges();
  }
  function selectAnalysis(id){if(!countries.has(id))return;bridge().set({country:id},false);const rows=root.ATLAS_ANALYSIS_RESULT.rows;$('#pro-selected').innerHTML=recordView(rows);const r=selectedRecord(rows),c=charts.get('pro-scatter');if(c)c.setOption({series:[...regions.map(()=>({})),{label:{formatter:()=>name(id)},data:r?[{id,value:[r.x,r.y]}]:[]}]});renderChanges();}
  function renderChanges(){const s=state(),m=D.metrics[s.yMetric],ys=m.years,el=$('#pro-changes');if(!el)return;
    const rows=s.changeStart<s.changeEnd?M.changes(D,m.id,s.changeStart,s.changeEnd,s.analysisRegion):[],sorted=rows.slice().sort((a,b)=>b.delta-a.delta),median=sorted.length?root.d3.median(sorted,r=>r.delta):null,selected=rows.find(r=>r.id===s.country),unit=m.unit==='percent'?t('pp'):bridge().unit(m);
    root.ATLAS_CHANGE_RESULT={rows,metric:m.id,unit,median,start:s.changeStart,end:s.changeEnd};
    const extremes=[...sorted.slice(0,6),...sorted.slice(-6)].filter((r,i,a)=>a.findIndex(x=>x.id===r.id)===i).sort((a,b)=>b.delta-a.delta);
    el.innerHTML=`<div class="pro-section-head"><div><h2>${text('changeTitle')}</h2><p>${esc(metricName(m.id))}</p></div><div class="pro-endpoints"><div class="field"><label for="pro-from">${text('startYear')}</label><select id="pro-from">${ys.map(y=>`<option${y===s.changeStart?' selected':''}>${y}</option>`).join('')}</select></div><div class="field"><label for="pro-to">${text('endYear')}</label><select id="pro-to">${ys.map(y=>`<option${y===s.changeEnd?' selected':''}>${y}</option>`).join('')}</select></div></div></div>${notice('changeNote')}<div class="pro-stat-row">${stat(t('matched'),String(rows.length))}${stat(t('medianChange'),decimal(median),unit)}${stat(t('selectedChange'),decimal(selected?.delta),name(s.country)+' · '+unit)}</div><p class="small muted">${text('extremesCaption')}</p><div id="pro-change-chart" class="pro-chart pro-change-chart"></div><details class="pro-table-details"><summary>${text('allRows')} · ${rows.length}</summary><div class="table-scroll"><table class="data-table"><thead><tr><th>${text('country')}</th><th>${s.changeStart}</th><th>${s.changeEnd}</th><th>Δ · ${esc(unit)}</th></tr></thead><tbody>${sorted.map(r=>`<tr><td>${esc(name(r.id))}</td><td>${format(r.from,m)}</td><td>${format(r.to,m)}</td><td>${decimal(r.delta)}</td></tr>`).join('')}</tbody></table></div></details>`;
    if(!rows.length){$('#pro-change-chart').innerHTML=`<div class="empty">${text('needYears')}</div>`;return;}
    const c=theme(),base=baseChart();chart('pro-change-chart',{...base,grid:{top:20,left:155,right:70,bottom:35},xAxis:{type:'value',name:unit,nameLocation:'middle',nameGap:23,axisLabel:{color:c.muted},splitLine:{lineStyle:{color:c.line}}},yAxis:{type:'category',data:extremes.map(r=>name(r.id)),inverse:true,axisLabel:{color:c.ink,width:140,overflow:'truncate',fontSize:11},axisLine:{show:false},axisTick:{show:false}},tooltip:{...base.tooltip,formatter:p=>`${esc(name(extremes[p.dataIndex].id))}<br>Δ ${decimal(p.value)} ${esc(unit)}<br>${s.changeStart} → ${s.changeEnd}`},series:[{type:'bar',barMaxWidth:17,label:{show:true,position:'right',formatter:p=>Number(p.value).toFixed(2),color:c.ink,fontSize:10},data:extremes.map(r=>({value:r.delta,itemStyle:{color:r.delta>=0?c.orange:c.accent}}))}]});
  }
  function chosenItems(){const s=state(),p=bridge().panel(),items=p.items.filter(i=>!s.off.includes(i.id)).map(i=>({...i,p:i.p*((s.target==='all'||s.target===i.id)?1-s.reduction:1)}));
    if(s.panel==='country')items.forEach(i=>{const m=i.id==='diabetes_who'?'diabetes_who_c':'obesity_c',v=M.observation(D,m,s.country,2022),f=(s.target==='all'||s.target===i.id)?1-s.reduction:1;if(v&&v[2]!=null&&v[3]!=null){i.low=v[2]/100*f;i.high=v[3]/100*f;}});
    return items;
  }
  function enhanceLab(){const el=$('#lab-results');if(!el||!root.ATLAS_LAST_RESULT||el.querySelector('.empty'))return;let box=$('#pro-lab-depth');if(!box){box=document.createElement('section');box.id='pro-lab-depth';box.className='pro-lab-depth';el.appendChild(box);}const items=chosenItems(),s=state();
    const env=M.endpointEnvelope(items,s.rho,Q,E),lim=M.bounds(items.map(x=>x.p));
    box.innerHTML=`<section class="plot-panel"><div class="plot-head"><h3>${text('sensitivityTitle')}</h3><button class="btn" data-pro="pin-scenario">${text('pinScenario')}</button></div><p class="small muted">${text('sensitivityNote')}</p><div class="pro-range-fact"><span>${text('rangeNotCI')}</span><strong>${pct(lim.lower)} – ${pct(lim.upper)}</strong></div><div id="pro-sensitivity" class="pro-chart pro-sensitivity"></div><div class="pro-endpoint-box"><h4>${text('inputEnvelope')}</h4>${env?`<div class="pro-envelope-values"><div>${text('stressMean')}<strong>${decimal(env.mean[0])} – ${decimal(env.mean[1])}</strong></div><div>${text('stressZero')}<strong>${pct(env.zero[0])} – ${pct(env.zero[1])}</strong></div></div><p>${text('envelopeNote')}</p>`:`<p>${text('noIntervals')}</p>`}</div></section>${items.length===2?`<section class="plot-panel pro-overlap"><h3>${text('overlapTitle')}</h3><p class="small muted">${text('overlapNote')}</p><p class="small">A: ${esc(t(items[0].id))} · B: ${esc(t(items[1].id))}</p><label for="pro-overlap">${text('overlapLabel')} <strong id="pro-overlap-value"></strong></label><input id="pro-overlap" type="range" min="0" max="1000" step="1" value="${Math.round(overlapFraction*1000)}"><div id="pro-overlap-mosaic" class="pro-overlap-mosaic"></div><div id="pro-overlap-values" class="pro-overlap-values"></div></section>`:''}<section class="plot-panel"><div class="plot-head"><h3>${text('notebook')}</h3><button class="btn" data-pro="export-notebook">JSON ↓</button></div><p class="small muted">${text('notebookNote')}</p><div id="pro-notebook"></div></section>`;
    const steps=Array.from({length:17},(_,i)=>i*.05),ps=items.map(i=>i.p),points=steps.map(r=>[r,E.summarize(ps,r,Q).zero*100]);
    const low=env?steps.map(r=>[r,E.summarize(items.map(i=>i.high),r,Q).zero*100]):null,high=env?steps.map(r=>[r,E.summarize(items.map(i=>i.low),r,Q).zero*100]):null,c=theme(),base=baseChart();
    chart('pro-sensitivity',{...base,grid:{left:52,right:18,top:20,bottom:38},xAxis:{...base.xAxis,min:0,max:.8,name:'ρ',nameLocation:'end'},yAxis:{...base.yAxis,min:0,max:100,name:t('zero')+' (%)',nameTextStyle:{fontSize:10}},tooltip:{...base.tooltip,trigger:'axis',valueFormatter:v=>decimal(v)+'%'},series:[{type:'line',name:t('scenario'),showSymbol:false,lineStyle:{color:c.accent,width:3},data:points,markLine:{symbol:'none',label:{formatter:'ρ = '+s.rho.toFixed(2),color:c.muted},lineStyle:{color:c.orange,type:'dashed'},data:[{xAxis:s.rho}]}}].concat(env?[{type:'line',name:t('inputEnvelope')+' −',showSymbol:false,lineStyle:{color:c.muted,type:'dashed',width:1},data:low},{type:'line',name:t('inputEnvelope')+' +',showSymbol:false,lineStyle:{color:c.muted,type:'dashed',width:1},data:high}]:[])});
    root.ATLAS_SENSITIVITY_RESULT={items,bounds:lim,envelope:env,points};renderOverlap();renderNotebook();
  }
  function renderOverlap(){const el=$('#pro-overlap-mosaic');if(!el)return;const items=chosenItems();if(items.length!==2)return;const p=items[0].p,q=items[1].p,lo=Math.max(0,p+q-1),hi=Math.min(p,q),r=M.joint(p,q,lo+(hi-lo)*overlapFraction);root.ATLAS_OVERLAP_RESULT=r;
    $('#pro-overlap-value').textContent=pct(r.both);$('#pro-overlap').disabled=hi===lo;$('#pro-overlap').setAttribute('aria-valuetext',pct(r.both));
    const values=[['neither',r.neither,'#d9e4d6'],['onlyA',r.onlyA,'#77a18c'],['onlyB',r.onlyB,'#dca76b'],['both',r.both,'#28574d']];
    el.innerHTML=values.map(([k,v,color])=>`<span style="width:${v*100}%;background:${color}" title="${text(k)}: ${pct(v)}"></span>`).join('');
    $('#pro-overlap-values').innerHTML=values.map(([k,v,color])=>`<div><span><i style="background:${color}"></i>${text(k)}</span><strong>${pct(v)}</strong></div>`).join('');
  }
  async function exportScatter(){
    const c=charts.get('pro-scatter');if(!c)return;const s=state(),image=new Image();
    image.src=c.getDataURL({type:'png',pixelRatio:2,backgroundColor:theme().paper});await image.decode();
    const canvas=document.createElement('canvas');canvas.width=image.width;canvas.height=image.height+160;const ctx=canvas.getContext('2d');ctx.fillStyle=theme().paper;ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(image,0,0);ctx.fillStyle=theme().ink;ctx.font='24px sans-serif';
    ctx.fillText('Health Atlas · '+metricName(s.x)+' × '+metricName(s.yMetric)+' · '+s.analysisYear,25,image.height+42,canvas.width-50);ctx.font='17px sans-serif';
    ctx.fillText(D.metrics[s.x].code+' / '+D.metrics[s.yMetric].code+' · Snapshot '+D.meta.retrieved,25,image.height+80,canvas.width-50);ctx.fillText(t('ecological'),25,image.height+118,canvas.width-50);
    const a=document.createElement('a');a.href=canvas.toDataURL('image/png');a.download='health-atlas-association-'+s.analysisYear+'.png';a.click();
  }
  function readNotebook(){try{const values=JSON.parse(localStorage.getItem('atlas-v4-notebook')||'[]');return Array.isArray(values)?values.filter(v=>v&&v.schema===1&&typeof v.url==='string'&&v.url.startsWith('#simulator?')&&typeof v.id==='string'&&v.id.length<60&&Number.isFinite(v.mean)&&v.mean>=0&&v.mean<=12&&Number.isFinite(v.zero)&&v.zero>=0&&v.zero<=1&&Number.isFinite(v.rho)&&v.rho>=0&&v.rho<=.8&&countries.has(v.country)&&typeof v.cohort==='string').slice(0,6):[];}catch{return [];}}
  function writeNotebook(values){try{localStorage.setItem('atlas-v4-notebook',JSON.stringify(values));return true;}catch{bridge().toast(t('storageUnavailable'));return false;}}
  function pinScenario(){const vals=readNotebook();if(vals.length===6){bridge().toast(t('savedFull'));return;}const s=state(),r=root.ATLAS_LAST_RESULT,p=bridge().panel();if(!r)return;vals.push({schema:1,id:String(Date.now())+'-'+Math.random().toString(36).slice(2,7),url:location.hash,cohort:s.panel,country:s.panel==='country'?s.country:s.panel==='SG5'?'SGP':'CHN',year:p.year,conditions:chosenItems().map(i=>i.id),rho:s.rho,reduction:s.reduction,mean:r.result.mean,zero:r.result.zero,dataVersion:D.meta.version,retrieved:D.meta.retrieved});if(writeNotebook(vals)){renderNotebook();bridge().toast(t('saved'));}}
  function renderNotebook(){const el=$('#pro-notebook');if(!el)return;const vals=readNotebook();el.innerHTML=vals.length?`<div class="table-scroll"><table class="data-table"><thead><tr><th>${text('panel')}</th><th>${text('average')}</th><th>${text('zero')}</th><th></th></tr></thead><tbody>${vals.map(v=>`<tr><td>${esc(name(v.country))}<br><small>${esc(v.cohort)} · ${esc(v.year)} · ρ ${decimal(v.rho)}</small></td><td>${decimal(v.mean)}</td><td>${pct(v.zero)}</td><td><button class="source-link" data-pro-restore="${esc(v.id)}">${text('restore')}</button> · <button class="source-link" data-pro-remove="${esc(v.id)}">${text('remove')}</button></td></tr>`).join('')}</tbody></table></div>`:`<p class="small muted">${text('notebookEmpty')}</p>`;}
  function enhanceAudit(){if($('#pro-audit'))return;const el=document.createElement('section');el.id='pro-audit';el.className='pro-audit';const year=new Date().getFullYear();
    el.innerHTML=`<div class="pro-section-head"><div><h2>${text('auditTitle')}</h2><p>${text('auditNote')}</p></div></div><div class="table-scroll"><table class="data-table"><thead><tr><th>${text('indicator')}</th><th>${text('observedLag')}</th><th>${text('yearLag')} (${year})</th><th>${text('sourceUpdate')}</th><th>${text('snapshotDate')}</th></tr></thead><tbody>${D.order.map(id=>{const m=D.metrics[id],a=M.sourceAge(m,year);return `<tr><td><button class="source-link" data-source="${id}">${esc(metricName(id))}</button><br><small>${text(m.age)} · ${text(m.measure)}</small></td><td>${a.latestYear}</td><td><span class="pro-lag" style="--lag:${Math.min(100,a.yearLag*12)}%">${a.yearLag}</span></td><td>${esc(a.sourceUpdated?.slice(0,10)||'—')}</td><td>${D.meta.retrieved}</td></tr>`;}).join('')}</tbody></table></div><p class="small muted">${text('modelVersion')} · 4.0.0 / ${D.meta.version} · ${text('uiUpgrade')}</p>`;
    const at=$('#content .hero');at.after(el);
  }
  function enhanceCompare(){if($('#pro-common-year'))return;const b=document.createElement('button');b.id='pro-common-year';b.className='btn';b.textContent=t('commonYear');b.dataset.pro='common-year';const years=M.commonYears(D,state().metric,state().compare);b.disabled=!years.length;b.title=years.length?String(years.at(-1)):t('noCommon');$('.compare-controls')?.appendChild(b);}
  function enhance(){clearTimeout(enhanceTimer);enhanceTimer=setTimeout(()=>{if(!bridge())return;prune();const s=state();if(s.page==='simulator')enhanceLab();else if(s.page==='data')enhanceAudit();else if(s.page==='compare')enhanceCompare();else if(s.page==='world'){
      if(!$('#pro-jump')){const link=document.createElement('button');link.id='pro-jump';link.className='btn btn-primary';link.dataset.nav='insights';link.textContent=t('goInsights');$('.page-tools')?.prepend(link);}
      if(s.view==='globe'){$('#map-notes')?.appendChild(document.createTextNode(' '+t('sphereNote')));}
    }},90);}
  document.addEventListener('change',e=>{const id=e.target.id,s=bridge()?.state();if(!s)return;
    if(id==='pro-x'||id==='pro-y'){const patch=id==='pro-x'?{x:e.target.value}:{yMetric:e.target.value};const next={...s,...patch},ys=D.metrics[next.x].years.filter(y=>D.metrics[next.yMetric].years.includes(y));patch.analysisYear=ys.includes(s.analysisYear)?s.analysisYear:ys.at(-1);patch.changeEnd=patch.analysisYear;patch.changeStart=D.metrics[next.yMetric].years.filter(y=>y<patch.changeEnd).find(y=>y>=2010)||D.metrics[next.yMetric].years[0];bridge().set(patch);}
    else if(id==='pro-year')bridge().set({analysisYear:Number(e.target.value)});
    else if(id==='pro-region')bridge().set({analysisRegion:e.target.value});
    else if(id==='pro-from'||id==='pro-to'){bridge().set(id==='pro-from'?{changeStart:Number(e.target.value)}:{changeEnd:Number(e.target.value)},false);renderChanges();}
  });
  document.addEventListener('input',e=>{if(e.target.id==='pro-overlap'){overlapFraction=Number(e.target.value)/1000;renderOverlap();}});
  document.addEventListener('click',e=>{if(!bridge())return;const preset=e.target.closest('[data-pro-preset]');if(preset){const [x,yMetric]=preset.dataset.proPreset.split('|');const years=D.metrics[x].years.filter(y=>D.metrics[yMetric].years.includes(y));bridge().set({x,yMetric,analysisYear:years.at(-1),changeStart:2010,changeEnd:years.at(-1)});return;}
    const country=e.target.closest('[data-pro-country]');if(country){selectAnalysis(country.dataset.proCountry);return;}
    const remove=e.target.closest('[data-pro-remove]');if(remove){writeNotebook(readNotebook().filter(v=>v.id!==remove.dataset.proRemove));renderNotebook();return;}
    const restore=e.target.closest('[data-pro-restore]');if(restore){const v=readNotebook().find(v=>v.id===restore.dataset.proRestore);if(v){location.hash=v.url;root.dispatchEvent(new HashChangeEvent('hashchange'));}return;}
    const action=e.target.closest('[data-pro]')?.dataset.pro;
    if(action==='export-scatter')exportScatter().catch(()=>bridge().toast(t('graphFallback')));
    else if(action==='export-analysis'&&lastAnalysis)download({...lastAnalysis,changes:root.ATLAS_CHANGE_RESULT},'health-atlas-analysis.json');
    else if(action==='pin-scenario')pinScenario();
    else if(action==='export-notebook')download({schema:'health-atlas-notebook/1',scenarios:readNotebook(),note:t('notebookNote')},'health-atlas-scenarios.json');
    else if(action==='common-year'){const s=state(),years=M.commonYears(D,s.metric,s.compare);if(years.length)bridge().set({year:years.at(-1)});}
  });
  root.addEventListener('pagehide',cleanup);
  root.AtlasPro={readParams,writeParams,createGlobe,renderInsights,enhance,cleanup,version:'4.0.0',debug:{load,charts,globe:()=>globe,readNotebook}};
})(window);
